version: '3.9'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80
    depends_on:
      - db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-ec2
      # ↓gemファイルの永続化
      # ↓gem environmentコマンドでinstration directoryのパスを指定する
      - bundle:/Library/Ruby/Gems/2.6.0
    ports:
      - '3000:3000'
    depends_on:
      - db
  smtp:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
# ↓gemファイルの永続化設定
volumes:
  bundle:
