default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db

development:
  <<: *default
  database: rails-demo2_development

test:
  <<: *default
  database: rails-demo2_test

production:
  <<: *default
    url: <%= ENV['DATABASE_URL'] %>
